"""empty message

Revision ID: 2016a6a453e2
Revises: e3468783be2c
Create Date: 2025-05-10 20:17:42.408831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2016a6a453e2'
down_revision = 'e3468783be2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'document_master', ['invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
