"""empty message

Revision ID: c31b167bbc0e
Revises: 
Create Date: 2025-05-03 14:07:56.275252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c31b167bbc0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_add_on', sa.Boolean(), nullable=True))
        batch_op.alter_column('sku',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sports_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sports_experience', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_add_on')

    # ### end Alembic commands ###
