"""empty message

Revision ID: e3468783be2c
Revises: c31b167bbc0e
Create Date: 2025-05-04 12:31:52.863448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3468783be2c'
down_revision = 'c31b167bbc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_document_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_document_master', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
